### ISSUE TITLE
Indicator is broken on ubuntu 17.10

### ISSUE THREAD

**Issue by Doofitator** [Doofitator/Doofitator-Power#1]
Traceback (most recent call last):
      File "Doofitator-Power.py", line 13, in <module>
        gi.require_version('AppIndicator3', '0.1')
      File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 118, in require_version
        raise ValueError('Namespace %s not available' % namespace)
    ValueError: Namespace AppIndicator3 not available

**Comment by Doofitator** [comment]
RESOLVED. See updated README.md
